### ISSUE TITLE
Support different refs for core/extras submodules in ansible_ref_require

### ISSUE THREAD

**Issue by toopy** [novafloss/ansible-setup#11]
``` bash
+ ansible_ref_require v2.1.2.0
+ local ansible_ref=v2.1.2.0
+ local ansible_bin=
+ local ansible_path=/home/florent/.ansible-env/src/ansible
+ echo Requiring ansible ref v2.1.2.0 in /home/florent/.ansible-env/src/ansible
Requiring ansible ref v2.1.2.0 in /home/florent/.ansible-env/src/ansible
+ ansible_dependencies_require
+ virtualenv_require
+ local pip_min_version=8
+ local setuptools_min_version=20
++ get
++ hash virtualenv2
++ hash virtualenv
++ echo virtualenv
+ '[' -z virtualenv ']'
++ get
++ hash virtualenv2
++ hash virtualenv
++ echo virtualenv
+ VIRTUALENV=virtualenv
+ '[' '!' -d /home/florent/.ansible-env ']'
+ PYTHON=/home/florent/.ansible-env/bin/python
+ PIP=/home/florent/.ansible-env/bin/python
++ major_version pip
+++ get_python
+++ echo /home/florent/.ansible-env/bin/python
++ /home/florent/.ansible-env/bin/python -c 'import pip; print pip.__version__.split('\''.'\'')[0]'
+ '[' 8 -ge 8 ']'
++ major_version setuptools
+++ get_python
+++ echo /home/florent/.ansible-env/bin/python
++ /home/florent/.ansible-env/bin/python -c 'import setuptools; print setuptools.__version__.split('\''.'\'')[0]'
+ '[' 28 -ge 20 ']'
+ python2_require
+ hash python2
+ return
+ python2_crypto_require
++ get_python
++ echo /home/florent/.ansible-env/bin/python
+ /home/florent/.ansible-env/bin/python -c 'import Crypto'
+ return
++ get_pip
++ echo /home/florent/.ansible-env/bin/pip
+ /home/florent/.ansible-env/bin/pip install jinja2 PyYAML
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /home/florent/.ansible-env/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /home/florent/.ansible-env/lib/python2.7/site-packages (from jinja2)
+ ((  1 < 1  ))
+ apt_get_install ca-certificates
+ (( n=0 ))
+ (( n<=22 ))
+ sudo apt-get -y install ca-certificates
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
ca-certificates is already the newest version (20160104).
Les paquets suivants ont été installés automatiquement et ne sont plus nécessaires :
  gir1.2-evince-3.0 libpth20
Veuillez utiliser « sudo apt autoremove » pour les supprimer.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 166 non mis à jour.
+ return 0
++ mktemp -d
+ tmp=/tmp/tmp.n5LwqN0AwZ
+ pushd /tmp/tmp.n5LwqN0AwZ
/tmp/tmp.n5LwqN0AwZ ~/work/jenkins-front/ansible
+ popd
~/work/jenkins-front/ansible
++ github_url ansible-modules-core v2.1.2.0
++ echo https://codeload.github.com/ansible/ansible-modules-core/tar.gz/v2.1.2.0
++ github_url ansible-modules-extras v2.1.2.0
++ echo https://codeload.github.com/ansible/ansible-modules-extras/tar.gz/v2.1.2.0
++ jobs -r
+ download_extract https://codeload.github.com/ansible/ansible-modules-core/tar.gz/v2.1.2.0
+ download_extract https://codeload.github.com/ansible/ansible-modules-extras/tar.gz/v2.1.2.0
+ python -c 'import tarfile,urllib2; tarfile.open(fileobj=urllib2.urlopen('\''https://codeload.github.com/ansible/ansible-modules-core/tar.gz/v2.1.2.0'\''), mode='\''r|gz'\'').extractall()'
+ python -c 'import tarfile,urllib2; tarfile.open(fileobj=urllib2.urlopen('\''https://codeload.github.com/ansible/ansible-modules-extras/tar.gz/v2.1.2.0'\''), mode='\''r|gz'\'').extractall()'
++ github_url ansible v2.1.2.0
++ echo https://codeload.github.com/ansible/ansible/tar.gz/v2.1.2.0
++ tr -d ' '
+ download_extract https://codeload.github.com/ansible/ansible/tar.gz/v2.1.2.0
++ wc -l
+ python -c 'import tarfile,urllib2; tarfile.open(fileobj=urllib2.urlopen('\''https://codeload.github.com/ansible/ansible/tar.gz/v2.1.2.0'\''), mode='\''r|gz'\'').extractall()'
+ [[ 3 -eq 0 ]]
+ sleep .1
++ jobs -r
++ tr -d ' '
++ wc -l
+ [[ 3 -eq 0 ]]
+ sleep .1
++ jobs -r
++ wc -l
++ tr -d ' '
+ [[ 3 -eq 0 ]]
+ sleep .1
++ jobs -r
++ wc -l
++ tr -d ' '
+ [[ 3 -eq 0 ]]
+ sleep .1
++ jobs -r
++ wc -l
++ tr -d ' '
+ [[ 3 -eq 0 ]]
+ sleep .1
++ jobs -r
++ wc -l
++ tr -d ' '
+ [[ 3 -eq 0 ]]
+ sleep .1
++ jobs -r
++ wc -l
++ tr -d ' '
+ [[ 3 -eq 0 ]]
+ sleep .1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
Traceback (most recent call last):
Traceback (most recent call last):
      File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
        response = meth(req, response)
response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
        'http', request, response, code, msg, hdrs)
'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    return self._call_chain(*args)
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
    result = func(*args)
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPErrorurllib2.HTTPError: HTTP Error 404: Not Found: 
HTTP Error 404: Not Found
```

**Comment by jpic** [comment]
Can we close this now that ansible does not use submodules anymore ?
